# Generated by Django 4.2.15 on 2024-08-19 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='zadach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Специальности')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zadachi', to='zadach.listspec')),
            ],
        ),
    ]
