# Generated by Django 4.2.15 on 2024-08-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0003_spec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listspec',
            old_name='name',
            new_name='title',
        ),
    ]
