# Generated by Django 4.2.15 on 2024-08-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0004_rename_name_listspec_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule201',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=9)),
                ('time', models.TimeField()),
                ('subject', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255)),
                ('classroom', models.CharField(max_length=50)),
            ],
        ),
    ]
