# Generated by Django 4.2.15 on 2024-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0005_schedule201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule201',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
