# Generated by Django 4.2.15 on 2024-08-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0006_alter_schedule201_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule201',
            name='time',
        ),
    ]
