# Generated by Django 4.2.15 on 2024-08-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0007_remove_schedule201_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listspec',
            name='rasp',
            field=models.ManyToManyField(related_name='zadachi', to='zadach.schedule201'),
        ),
    ]
