# Generated by Django 4.2.15 on 2024-08-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0008_listspec_rasp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listspec',
            name='rasp',
        ),
        migrations.AddField(
            model_name='schedule201',
            name='list_par',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='zadach.listspec'),
        ),
    ]
