# Generated by Django 4.2.15 on 2024-08-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0009_remove_listspec_rasp_schedule201_list_par'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule201',
            old_name='list_par',
            new_name='list_groups',
        ),
    ]
