# Generated by Django 4.2.15 on 2024-08-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0013_alter_listspec_list_par'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spec',
        ),
    ]
