# Generated by Django 4.2.15 on 2024-08-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0014_delete_spec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule231',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=9)),
                ('subject', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255)),
                ('classroom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='listspec',
            name='list_par231',
            field=models.ManyToManyField(related_name='schedules', to='zadach.schedule231'),
        ),
    ]
