# Generated by Django 4.2.15 on 2024-08-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0015_schedule231_listspec_list_par231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listspec',
            name='list_par231',
        ),
        migrations.AlterField(
            model_name='listspec',
            name='list_par',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='zadach.schedule201'),
        ),
    ]
