# Generated by Django 4.2.15 on 2024-08-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0018_remove_listspec_list_par231_schedule231_list_par231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule231',
            name='list_par231',
        ),
        migrations.AddField(
            model_name='listspec',
            name='list_par231',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='zadach.schedule231'),
        ),
    ]
