# Generated by Django 4.2.15 on 2024-08-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0019_remove_schedule231_list_par231_listspec_list_par231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule202',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=9)),
                ('subject', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255)),
                ('classroom', models.CharField(max_length=50)),
            ],
        ),
    ]
