# Generated by Django 4.2.15 on 2024-08-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0022_listgroup_schedule101_schedule111_schedule121_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeUR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Время урока')),
            ],
        ),
    ]
