# Generated by Django 4.2.15 on 2024-08-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0023_timeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeur',
            name='title1',
            field=models.CharField(default='default_value', max_length=255, verbose_name='Время урока №2'),
        ),
        migrations.AddField(
            model_name='timeur',
            name='title2',
            field=models.CharField(default='default_value', max_length=255, verbose_name='Время урока №3'),
        ),
        migrations.AddField(
            model_name='timeur',
            name='title3',
            field=models.CharField(default='default_value', max_length=255, verbose_name='Время урока №4'),
        ),
        migrations.AddField(
            model_name='timeur',
            name='title4',
            field=models.CharField(default='default_value', max_length=255, verbose_name='Время урока №5'),
        ),
        migrations.AddField(
            model_name='timeur',
            name='title5',
            field=models.CharField(default='default_value', max_length=255, verbose_name='Время урока №6'),
        ),
        migrations.AddField(
            model_name='timeur',
            name='title6',
            field=models.CharField(default='default_value', max_length=255, verbose_name='Время урока №7'),
        ),
        migrations.AddField(
            model_name='timeur',
            name='title7',
            field=models.CharField(default='default_value', max_length=255, verbose_name='Время урока №8'),
        ),
        migrations.AddField(
            model_name='timeur',
            name='title8',
            field=models.CharField(default='default_value', max_length=255, verbose_name='Время урока №9'),
        ),
        migrations.AddField(
            model_name='timeur',
            name='title9',
            field=models.CharField(default='default_value', max_length=255, verbose_name='Время урока №10'),
        ),
        migrations.AlterField(
            model_name='timeur',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Время урока №1'),
        ),
    ]
