# Generated by Django 4.2.15 on 2024-08-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0024_timeur_title1_timeur_title2_timeur_title3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeur',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='timeur',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='timeur',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='timeur',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='timeur',
            name='title5',
        ),
        migrations.RemoveField(
            model_name='timeur',
            name='title6',
        ),
        migrations.RemoveField(
            model_name='timeur',
            name='title7',
        ),
        migrations.RemoveField(
            model_name='timeur',
            name='title8',
        ),
        migrations.RemoveField(
            model_name='timeur',
            name='title9',
        ),
    ]
