# Generated by Django 4.2.15 on 2024-08-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0025_remove_timeur_title1_remove_timeur_title2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeur',
            name='time',
            field=models.ManyToManyField(related_name='ListGroup', to='zadach.listgroup'),
        ),
        migrations.AlterField(
            model_name='timeur',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Время урока '),
        ),
    ]
