# Generated by Django 4.2.15 on 2024-08-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0026_timeur_time_alter_timeur_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeur',
            name='time',
        ),
        migrations.AddField(
            model_name='listgroup',
            name='time',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='zadach.timeur'),
        ),
    ]
