# Generated by Django 4.2.15 on 2024-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0027_remove_timeur_time_listgroup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPrepod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Фамилия И.О. преподавателя:')),
            ],
        ),
    ]
