# Generated by Django 5.1.4 on 2024-12-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0032_changedschedule_schedule131_time_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listgroup',
            name='time_subject',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='zadach.time_subject'),
        ),
    ]
