# Generated by Django 5.1.4 on 2025-02-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0033_listgroup_time_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listgroup',
            name='time_subject',
        ),
    ]
